substitutions:
  name: apc-ups
  device_description: "Monitor and control a APC UPS via RS232"
  external_components_source: github://MrC0nst/esphome-apc-ups@main
  tx_pin: GPIO16
  rx_pin: GPIO17

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-apc-ups"
    version: 1.0.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
logger:

# If you don't use Home Assistant please remove this `api` section and uncomment the `mqtt` component!
api:

# mqtt:
#   broker: !secret mqtt_host
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   id: mqtt_client

uart:
  - id: uart_0
    baud_rate: 2400
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
    debug:
      direction: BOTH
      dummy_receiver: false
      after:
        delimiter: "\n"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes);

apc_ups:
  - id: ups0
    uart_id: uart_0

binary_sensor:
  - platform: apc_ups
    apc_ups_id: ups0
    runtime_calibration:
      name: "${name} runtime calibration"
    smart_trim:
      name: "${name} smart trim"
    smart_boost:
      name: "${name} smart boost"
    on_line:
      name: "${name} on line"
    on_battery:
      name: "${name} on battery"
    output_overloaded:
      name: "${name} output overloaded"
    battery_low:
      name: "${name} battery low"
    replace_battery:
      name: "${name} replace battery"

sensor:
  - platform: apc_ups
    apc_ups_id: ups0
    battery_voltage:
      name: "${name} battery voltage"
    grid_frequency:
      name: "${name} grid frequency"
    grid_voltage:
      name: "${name} grid voltage"
    ac_output_voltage:
      name: "${name} ac output voltage"
    ac_output_load:
      name: "${name} ac output load"
    status_bitmask:
      name: "${name} status bitmask"
    state_of_charge:
      name: "${name} state of charge"
    estimated_runtime:
      name: "${name} estimated runtime"
    internal_temperature:
      name: "${name} internal temperature"
    ambient_temperature:
      name: "${name} ambient temperature"
    max_grid_voltage:
      name: "${name} max grid voltage"
    min_grid_voltage:
      name: "${name} min grid voltage"   
    ambient_humidity:
      name: "${name} ambient humidity"
    low_transfer_voltage:
      name: "${name} low transfer voltage"
    nominal_output_voltage:
      name: "${name} nominal output voltage"
    upper_transfer_voltage:
      name: "${name} upper transfer voltage"
    nominal_battery_voltage:
      name: "${name} nominal_battery_voltage"
    return_threshold:
      name: "${name} return_threshold"
      filters:
        - calibrate_linear:
           method: exact
           datapoints:
            - 0 -> 0
            - 1 -> 15
            - 2 -> 25
            - 3 -> 90

  - platform: apc_ups
    apc_ups_id: ups0
    cause_of_last_transfer:
      name: "${name} cause of last transfer"
      filters:
        - substitute:
          - "R -> неприемлемая скорость изменения напряжения сети" # unacce table utility voltage rate of change
          - "S -> передача по команде U или активация ИБП" #transfer due to U command or activation of UPS
          - "NA -> причина перевода по-прежнему недоступна" # прочитайте еще раз # transfer reason still not available; read again 
          - "H -> высокое напряжение сети" #high utility voltage
          - "L -> низкое напряжение сети" #low utility voltage
          - "T -> скачок напряжения" #line voltage notch or spike
          - "O -> никаких переходов с момента включения" #no transfers since turnon
    firmware_revision:
      name: "${name} firmware revision"
    manufacture_date:
      name: "${name} manufacture date"
    last_battery_change_date:
      name: "${name} last battery change date"
    serial_number:
      name: "${name} serial number"
    old_firmware_version:
      name: "${name} old firmware version"
 #   measure_upc_firmware:
 #     name: "${name} measure_upc_firmware"
 #   copyright_notice:
 #     name: "${name} copyright_notice"
    self_test_results:
      name: "${name} self_test_results"
      filters:
        - substitute:
          - "OK -> хорошая батарея" #good battery
          - "BT -> произошел сбой из-за недостаточной емкости" #failed due to insufficient capacity
          - "NG -> произошел сбой из-за перегрузки" #failed due to overload
          - "NO -> результаты отсутствуют (за последние 5 минут тест не проводился)" # no results available (no test performed in last 5 minutes
    alarm_delay:
      name: "${name} alarm_delay"
      filters:
        - substitute:
          - "0 -> Задержка в 5 секунд после отключения питания" #5 second delay after power fail
          - "T -> Задержка в 30 секунд" #30 second delay
          - "L -> сигнал тревоги только при низком заряде батареи" #alarm at low battery only
          - "N -> никакой тревоги" # no alarm
    line_quality:
      name: "${name} line_quality"
      filters:
        - substitute:
          - "00 -> неприемлемый" # unacceptable
          - "FF -> приемлемый" # acceptable
